### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by saxtuchi** [saxtuchi/protospace-38417#2]
https://protospace-38417.onrender.com

**Comment by motomuun** [comment]
@saxtuchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー管理機能**

- [x] **必須項目に適切な値を入力すると、ユーザーの新規登録ができること**
必須項目を全て入力しても、新規登録が出来ません。新規登録出来るように修正をお願いします。

※ログイン後の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yusuketono** [comment]
@saxtuchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### プロトタイプ投稿機能
- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**
画像を添付していない場合、下記の画面に遷移してしまいます。
その場に留まるように修正しましょう。
<img width="642" alt="スクリーンショット 2022-12-23 16 54 07" src="https://user-images.githubusercontent.com/51428519/209295824-d2f300f1-d395-4350-b70c-d86aec45589a.png">

#### プロトタイプ一覧表示機能
- [x] **プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者名の、4つの情報について表示できること**
画像を表示することができないので、表示できるように修正しましょう。

#### コメント機能
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラー画面に遷移してしまうので、留まるように修正しましょう。
<img width="709" alt="スクリーンショット 2022-12-23 17 01 03" src="https://user-images.githubusercontent.com/51428519/209296887-b2e96c22-625c-46c4-b946-3e223284dbbe.png">

#### その他
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーのプロトタイプ編集ページに遷移できてしまうので、トップページにリダイレクトされるよう修正しましょう。
```
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。
```

**Comment by motomuun** [comment]
@saxtuchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、以下は修正が出来ておりました。

- [x]  **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**

一方で、新たに以下の問題が発生しております。
ご確認の上、修正をお願いします。

[修正依頼箇所]
**プロトタイプ投稿機能**
- [x] **正しく投稿できた場合は、トップページへ遷移すること**
全ての項目を入力した状態で投稿すると、以下のエラーページに遷移します。投稿が完了し、トップページに遷移するように修正をお願いします。
<img width="1433" alt="スクリーンショット 2022-12-24 9 07 05" src="https://user-images.githubusercontent.com/65059944/209414654-a376d7f0-5e2d-453d-8fac-51bfc1b9f24c.png">

※前回修正依頼をお出しした、投稿後の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by saxtuchi** [comment]
ご確認いただきありがとうございます。
時間かかってしまいすみません。再度ご確認いただけますでしょうか。
宜しくお願いいたします。

**Comment by shodai-ito** [comment]
@saxtuchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回の修正箇所の修正が確認できました。
下記もう一箇所修正していただきたい箇所がございます。
以下のご確認をお願いします！

**[修正依頼箇所]**
**プロトタイプ一覧表示機能**
- [x] **プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者名の、4つの情報について表示できるようにしましょう**
現在、プロトタイプ名が正しく表示されていないため、投稿したプロトタイプ名が表示されるようにしましょう。
![スクリーンショット 2023-01-04 10 18 38](https://user-images.githubusercontent.com/62537107/210675333-b48424c5-0af6-4809-a14e-2a553ce77bab.png)

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
挙動確認を行い、修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by saxtuchi** [comment]
すみません、修正しましたのでご確認いただけますでしょうか。
宜しくお願いいたします。

**Comment by ghost** [comment]
@saxtuchi さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
